# Generated by Django 5.2.1 on 2026-01-04 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_name', models.CharField(help_text='ログイン用ID', max_length=50, unique=True, verbose_name='ユーザー名')),
                ('user_type', models.CharField(choices=[('student', '生徒'), ('guardian', '保護者'), ('staff', 'スタッフ'), ('administrator', '管理者')], max_length=20, verbose_name='ユーザータイプ')),
                ('full_name', models.CharField(max_length=50, verbose_name='表示名')),
                ('grade', models.IntegerField(blank=True, help_text='生徒の場合のみ', null=True, verbose_name='学年')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_staff', models.BooleanField(default=False, help_text='管理サイトへのアクセス権限', verbose_name='スタッフ権限')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'user',
            },
        ),
    ]
