# Generated by Django 5.2.1 on 2026-01-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_full_name_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', '生徒'), ('guardian', '保護者'), ('staff', 'スタッフ'), ('admin', '管理者')], max_length=20, verbose_name='ユーザータイプ'),
        ),
    ]
